name: multi_browser
description: Multi-session browser with GeckoView
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
